{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.xfail(condition=False, reason=\"\")\n    # 当条件为假,用例执行失败\n    def test_03():\n        print(\"当条件为假,用例执行失败\")\n>       assert False\nE       assert False\n\nscripts\\test_xfail.py:27: AssertionError"}, "start": 1578128102164, "stop": 1578128102164, "uuid": "41fd3262-e93b-4619-8b3f-402bc0b33a71", "historyId": "a7e5f780fd211a9908c869a33141a066", "testCaseId": "ff2aa1bb231e4a539dad56671b5d5635", "fullName": "scripts.test_xfail#test_03", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_xfail"}, {"name": "host", "value": "DESKTOP-TJSPRKG"}, {"name": "thread", "value": "15504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_xfail"}]}