{"name": "test_01", "status": "skipped", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.xfail(condition=True, reason=\"\")\n    def test_01():\n        print(\"当条件为真,用例执行失败\")\n>       assert False\nE       assert False\n\nscripts\\test_xfail.py:13: AssertionError"}, "start": 1578128102151, "stop": 1578128102151, "uuid": "9cbf7333-5e60-4688-ac20-e89da57b23b3", "historyId": "338cafb798c78aa01017fc0530e0dbe2", "testCaseId": "d8a815ffe8fc0ef303dcabee59dc1357", "fullName": "scripts.test_xfail#test_01", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_xfail"}, {"name": "host", "value": "DESKTOP-TJSPRKG"}, {"name": "thread", "value": "15504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_xfail"}]}